# Generated by Django 4.0.5 on 2022-07-12 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0003_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='codigo',
        ),
    ]
