# Generated by Django 4.0.4 on 2022-07-17 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carrito',
            new_name='CarritoModel',
        ),
    ]
